hello_d:main.cpp tb_vp.cpp sys_bus.cpp MyIP.cpp vp.cpp
	g++  `Magick++-config --cxxflags --cppflags` -O2 -Wall -I ${SYSTEMC}/include -L${SYSTEMC}/lib-linux64 -lsystemc \
	-o hello_d main.cpp tb_vp.cpp sys_bus.cpp MyIP.cpp vp.cpp `Magick++-config --ldflags --libs`


